services:
  # tama-web:
  #   container_name: tama-web
  #   depends_on:
  #     - tama-api
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev # Or Dockerfile.prod, as needed
  #   volumes:
  #     - ./frontend:/app # Mount the source code for live-reloading
  #     - /app/node_modules # Separate node_modules to avoid conflicts
  #   ports:
  #     - '3000:3000' # Expose development port
  #   environment:
  #     NODE_ENV: development # Set environment variable to development
  #     PORT: 3000 # Application port
  #     HOSTNAME: '0.0.0.0' # Allow access from all IP addresses
  #     PNPM_HOME: '/pnpm'
  #     PATH: '/pnpm:$PATH'
  #     NEXT_TELEMETRY_DISABLED: '1' # Disable telemetry
  #     AUTH_SECRET: wTFm+Txkfy/kbsrVQP8AsMIi3rD+d+LdQcFdXPTCYrRefHhBrsxEoJ7
  #     NEXT_PUBLIC_SERVER_URL: http://localhost:3000
  #     NEXT_PUBLIC_API_BASE_URL: http://192.168.1.130:8222/api/v1
  #     AUTH_TRUST_HOST: true

  #   command: pnpm dev # Run development mode with hot-reloading
  #   networks:
  #     - tama-network
  #   restart: unless-stopped

  # tama-api:
  #   container_name: tama-api
  #   depends_on:
  #     - tama_DB
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile.dev # Or Dockerfile.prod, as needed
  #   volumes:
  #     - ./server:/app # Mount the source code for live-reloading
  #     - /app/node_modules # Separate node_modules to avoid conflicts
  #   ports:
  #     - '8000:8000' # Expose development port
  #   environment:
  #     NODE_ENV: development # Set environment variable to development
  #     PORT: 8000 # Application port
  #     HOSTNAME: '0.0.0.0' # Allow access from all IP addresses

  #   command: npm run dev # Run development mode with hot-reloading
  #   networks:
  #     - tama-network
  #   restart: unless-stopped

  tama_DB:
    image: postgres:16-alpine3.19
    container_name: tama_DB
    environment:
      POSTGRES_USER: programmer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: litiko_services
      PGDATA: /data/postgres
    volumes:
      - tama_DB:/var/lib/postgresql/data
    ports:
      - '5437:5432'
    networks:
      - tama-network
    restart: unless-stopped

volumes:
  tama_DB:

networks:
  tama-network:
    driver: bridge
