
version: '3'

services:
  tama-web:
    container_name: tama-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_ENDPOINT: http://tama-api:8003

    image: tama-web
    restart: unless-stopped
    ports:
      - 3019:3019
    networks:
      - dockploy_network
    env_file:
      - ./apps/web/.env.prod

  tama-api:
    container_name: tama-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    image: tama-api
    restart: unless-stopped
    ports:
      - 8003:8003
    networks:
      - dockploy_network
    env_file:
      - ./apps/api/.env.prod

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dockploy_network:
    driver: bridge
