version: '3'

services:
  tama-web:
    container_name: tama-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_ENDPOINT: http://tama-api:8003

    image: tama-web
    restart: unless-stopped

    # ❌ Remove ports (Traefik handles access)
    ports:
      - 3019:3019

    networks:
      - dokploy-network

    env_file:
      - ./apps/web/.env.prod

    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network

      # HTTP
      - traefik.http.routers.tama-web.rule=Host(`tamalawi.com`) || Host(`www.tamalawi.com`)
      - traefik.http.routers.tama-web.entrypoints=web

      # HTTPS
      - traefik.http.routers.tama-websecure.rule=Host(`tamalawi.com`) || Host(`www.tamalawi.com`)
      - traefik.http.routers.tama-websecure.entrypoints=websecure
      - traefik.http.routers.tama-websecure.tls.certresolver=letsencrypt

      # ✅ REQUIRED
      - traefik.http.services.tama-web.loadbalancer.server.port=3019


  tama-api:
    container_name: tama-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile

    image: tama-api
    restart: unless-stopped

    networks:
      - dokploy-network

    env_file:
      - ./apps/api/.env.prod

    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network

      # HTTP
      - traefik.http.routers.tama-api.rule=Host(`api.tamalawi.com`)
      - traefik.http.routers.tama-api.entrypoints=web

      # HTTPS
      - traefik.http.routers.tama-apisecure.rule=Host(`api.tamalawi.com`)
      - traefik.http.routers.tama-apisecure.entrypoints=websecure
      - traefik.http.routers.tama-apisecure.tls.certresolver=letsencrypt

      # ✅ REQUIRED
      - traefik.http.services.tama-api.loadbalancer.server.port=8003


networks:
  dokploy-network:
    external: true